TAGDIR=/usr/local/apache/hotbiz/css
LOCALTAGDIR=${HOME}/public_html/ver46/css

default:
all:
clean:
depend:
cartsync:
rsvsync:
dbbsync:
instcart:
instrsv:
instdbb:

hbsync:
	install -c -m 644 *.css ${LOCALTAGDIR}

insthb:
	install -c -m 644 *.css ${TAGDIR}
