#!/bin/sh

/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/db/reserve/create_table.sql /usr/local/share/skel/as-blog/er-blog.sql

/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/reserve/admin/blog_editentry_buffer.skl /usr/local/apache/share/er-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/reserve/admin/blog_editentry.skl /usr/local/apache/share/er-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/reserve/admin/blog_delete_file_ask.skl /usr/local/apache/share/er-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/reserve/admin/blog_upload_movie.skl /usr/local/apache/share/er-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/reserve/admin/blog_entry_list.skl /usr/local/apache/share/er-blog/skeleton/
/bin/chmod 644 /usr/local/apache/share/er-blog/skeleton/*.skl

/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_01.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_02.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_03.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_04.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_05.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_06.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_07.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_08.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_09.css /usr/local/apache/share/er-blog/css/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/css/reserve/blog07_10.css /usr/local/apache/share/er-blog/css/
/bin/chmod 644 /usr/local/apache/share/er-blog/css/*.css

/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/icon_rental.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_01.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_02.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_03.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_04.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_05.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_06.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_07.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_08.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_09.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_blogtop_07_10.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_01.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_02.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_03.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_04.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_05.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_06.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_07.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_08.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_09.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/back_top_07_10.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_01.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_02.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_03.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_04.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_05.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_06.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_07.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_08.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_09.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/endline_07_10.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_01.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_02.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_03.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_04.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_05.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_06.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_07.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_08.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_09.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/minus_07_10.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_01.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_02.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_03.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_04.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_05.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_06.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_07.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_08.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_09.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/plus_07_10.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental01.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental02.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental03.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental04.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental05.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental06.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental07.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental08.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental09.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/rental10.gif /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_01.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_02.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_03.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_04.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_05.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_06.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_07.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_08.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_09.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/reserve/theme/title_07_10.jpg /usr/local/apache/share/er-blog/images/theme/
/bin/chmod 644 /usr/local/apache/share/er-blog/images/theme/*.gif
/bin/chmod 644 /usr/local/apache/share/er-blog/images/theme/*.jpg

/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/entry/blog_entry.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/commentlist/blog_comment_list.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/blog_ranking/blog_ranking.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/boofmarklet/blog_bookmarklet.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/category/blog_category.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/configure/blog_configure.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/entrylist/blog_entry_list.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/looks/blog_looks.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/menu/blog_menu.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/sidecontent/blog_sidecontent.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/manage/tblist/blog_tb_list.cgi /usr/local/apache/share/reserve/admin/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/user/build_html/blog_build_html.cgi /usr/local/apache/share/reserve/
