#!/bin/sh

/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/cartex/user/copyright.gif /usr/local/apache/share/as-blog/images/user/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/images/cartex/admin/copyright.gif /usr/local/apache/share/as-blog/images/admin
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_bookmarklet.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_category_edit.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_category_list.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_category_list_empty.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_comment_list.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_configure.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_editentry.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_editentry_buffer.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_entry_import.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_entry_list.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_linkitem.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_linklist.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_linklist_title.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_looks.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_looks_category.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_looks_preview_01.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_profile.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_rss.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_rss_new.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_sidecontent.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_topmenu.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/admin/blog_trackback_list.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/user/blog_article.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/user/blog_article_list.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/user/blog_search_result.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/user/blog_usertop_left.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/user/blog_usertop_right.skl /usr/local/apache/share/as-blog/skeleton/
/bin/cp /staff/work/dbb_blog/RELENG_4/dbb_blog/skeleton/cartex/user/blog_visitor_list.skl /usr/local/apache/share/as-blog/skeleton/
