SUPDIR=/usr/local/apache/hotbiz/images/blog/user

default:
all:
clean:
hbsync:
cartsync:
rsvsync:
dbbsync:
depend:
instdbb:
instcart:
instrsv:

insthb:
	install -c -m 644 -o root -g wheel *.gif ${SUPDIR}
