SUPDIR=/usr/local/apache/hotbiz/images/blog/theme

default:
all:
clean:
hbsync:
cartsync:
rsvsync:
dbbsync:
depend:
instcart:
instrsv:
instdbb:

insthb:
	install -c -m 644 -o root -g wheel *.gif ${SUPDIR}
	install -c -m 644 -o root -g wheel *.jpg ${SUPDIR}
